/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package home;

import class_input.cls_input_data;
import class_input.koneksi;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.*;
import java.sql.*;
import class_input.cls_register;
import java.awt.event.*;
import java.util.HashMap;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.*;
import net.sf.jasperreports.view.*;

/**
 *
 * @author KRISNA, FERDI, RIFAN, ABDUL, NABIL
 */
public class data_barang extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form input_data
     */
    public data_barang() {
        initComponents();
        autonumber();
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        
        this.setLocation(x, y);
    }
public void ViewData(){
    cls_input_data idm = new cls_input_data();
    try{
        jTable1.setModel(DbUtils.resultSetToTableModel(idm.UpdateJTable()));
        
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bcetak = new javax.swing.JButton();
        bkembali = new javax.swing.JButton();
        txcari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbedit = new javax.swing.JButton();
        cbhapus = new javax.swing.JButton();
        cbrefresh = new javax.swing.JButton();
        cbsimpan = new javax.swing.JButton();
        label4 = new java.awt.Label();
        txjumlah = new java.awt.TextField();
        label3 = new java.awt.Label();
        cbkondisi = new javax.swing.JComboBox<>();
        txnm_barang = new java.awt.TextField();
        label2 = new java.awt.Label();
        txkode_brg = new java.awt.TextField();
        label1 = new java.awt.Label();
        cfilter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVENTARIS BARANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 80));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bcetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book_shiftright_default.png"))); // NOI18N
        bcetak.setText("Cetak");
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });

        bkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow_dark_left_stretch.png"))); // NOI18N
        bkembali.setText("kembali");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });

        txcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcariActionPerformed(evt);
            }
        });
        txcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txcariKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifyingGlass.png"))); // NOI18N
        jLabel2.setText(" ");

        cbedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book_edit_default.png"))); // NOI18N
        cbedit.setText("Edit");
        cbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbeditActionPerformed(evt);
            }
        });

        cbhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book_trash_default.png"))); // NOI18N
        cbhapus.setText("Hapus");
        cbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhapusActionPerformed(evt);
            }
        });

        cbrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        cbrefresh.setText("Refresh");
        cbrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrefreshActionPerformed(evt);
            }
        });

        cbsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/storageIconColor.png"))); // NOI18N
        cbsimpan.setText("Simpan");
        cbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsimpanActionPerformed(evt);
            }
        });

        label4.setAlignment(java.awt.Label.RIGHT);
        label4.setText("Jumlah");

        txjumlah.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txjumlahActionPerformed(evt);
            }
        });

        label3.setAlignment(java.awt.Label.RIGHT);
        label3.setText("Kondisi");

        cbkondisi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbkondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Jelek", "Rusak", "Rusak Parah" }));
        cbkondisi.setOpaque(false);
        cbkondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkondisiActionPerformed(evt);
            }
        });

        label2.setAlignment(java.awt.Label.RIGHT);
        label2.setText("Nama Barang");

        txkode_brg.setEditable(false);
        txkode_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txkode_brgActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.RIGHT);
        label1.setText("Kode Barang");

        cfilter.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cfilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cari Berdasarkan Nama Barang", "Cari Berdasarkan Kode Barang" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cfilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(bkembali)
                .addGap(32, 32, 32)
                .addComponent(bcetak)
                .addGap(122, 122, 122))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(cbsimpan))
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbkondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txnm_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txkode_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 113, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(cbrefresh)
                                .addGap(39, 39, 39)
                                .addComponent(cbhapus)
                                .addGap(30, 30, 30)
                                .addComponent(cbedit)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txkode_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txnm_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbkondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbsimpan)
                    .addComponent(cbrefresh)
                    .addComponent(cbhapus)
                    .addComponent(cbedit))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cfilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        label2.getAccessibleContext().setAccessibleName("");
        label2.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 770, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrefreshActionPerformed
        // TODO add your handling code here:
        try {
            conn = koneksi.getKoneksi();
            Statement stt = conn.createStatement();
            String sql="select * from inputdata order by kode_barang desc";
            ResultSet rs = stt.executeQuery(sql);
            if (rs.next()){
                String no_brg = rs.getString("kode_barang").substring(3);
                String AN = "" + (Integer.parseInt(no_brg) + 1);
                String Nol = "";
                
                if(AN.length()==1){
                    Nol = "000";
                } else if(AN.length()==2){
                    Nol = "00";
                } else if(AN.length()==3){
                    Nol = "0";
                } else if(AN.length()==4){
                    Nol = "";
                }
                
                txkode_brg.setText("BRG" + Nol + AN);
                  
            } else {
                txkode_brg.setText("BRG0001");
            }
//            rs.close();
//            conn.close();
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
//        txkode_brg.setText("");
        txnm_barang.setText("");
//        cbkondisi.setSelectedItem("");
//        cbkondisi.getSelectedItem();
        txjumlah.setText("");
        
        
        data_barang file=new data_barang();
        file.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_cbrefreshActionPerformed

    private void cbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhapusActionPerformed
        // TODO add your handling code here:
        String ObjButtons[]={"yes", "no"};
        int PromptResult = JOptionPane.showOptionDialog(null, "hapus ?", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, ObjButtons, ObjButtons[1]);
        if(PromptResult==0){
            cls_input_data idm = new cls_input_data();
            idm.kode_barang = txkode_brg.getText();
            try{
                idm.hapus();
                JOptionPane.showMessageDialog(null, "berhasil dihapus");
                ViewData();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_cbhapusActionPerformed

    private void AmbilKondisi(String kondisi) {
        String[]kds = {"Baik", "Jelek", "Rusak", "Rusak Parah"};
        cbkondisi.removeAllItems();
        cbkondisi.addItem(kondisi);
        for(int i = 0;i< kds.length;i++){
            if(kds[1].equals(kondisi)){
                cbkondisi.addItem(kds[i]);
            }
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ViewData();
    }//GEN-LAST:event_formWindowOpened

    private void cbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbeditActionPerformed
        // TODO add your handling code here:
        cls_input_data idm = new cls_input_data();
        idm.kode_barang = txkode_brg.getText();
        idm.nama_barang = txnm_barang.getText();
        idm.kondisi = (String)cbkondisi.getSelectedItem();
        idm.jumlah = txjumlah.getText();
        try{
            idm.edit();
            JOptionPane.showMessageDialog(null, "berhasil di ubah");
            ViewData();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cbeditActionPerformed

    private void txcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txcariActionPerformed

    private void txcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txcariKeyReleased
        // TODO add your handling code here:
        
        if(cfilter.getSelectedItem() == "Cari Berdasarkan Nama Barang"){
        
            String nama = txcari.getText();
            cls_input_data idm = new cls_input_data();
            try{
                jTable1.setModel(DbUtils.resultSetToTableModel(idm.SearchTextList(nama)));
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        }
        
        
        else {
            
            String kode = txcari.getText();
            cls_register idm = new cls_register();
            try{
                jTable1.setModel(DbUtils.resultSetToTableModel(idm.SearchTextList(kode)));
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        
        
    }//GEN-LAST:event_txcariKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        txkode_brg.setText(jTable1.getModel().getValueAt(row, 0).toString());
        txnm_barang.setText(jTable1.getModel().getValueAt(row, 1).toString());
        String kondisi = jTable1.getModel().getValueAt(row, 2).toString();
        AmbilKondisi(kondisi);
        txjumlah.setText(jTable1.getModel().getValueAt(row, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void txjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txjumlahActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        // TODO add your handling code here:
        
        try {
            String Driver = "com.mysql.jdbc.Driver";
            String koneksi = "jdbc:mysql://localhost/userlogin";
            String user = "root";
            String password = "";
            
            HashMap hash = new HashMap();
            Class.forName(Driver);
            
            Connection con = DriverManager.getConnection(koneksi, user, password);
            File file = new File("src/home/report_data.jasper");
            JasperReport jasperReport = (JasperReport)JRLoader.loadObject(file.getPath());
            JasperPrint jp = JasperFillManager.fillReport(jasperReport, hash, con);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
    }//GEN-LAST:event_bcetakActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_bkembaliActionPerformed

    private void cbkondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkondisiActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_cbkondisiActionPerformed

    private void cbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsimpanActionPerformed
        // TODO add your handling code here:
        cls_input_data idm = new cls_input_data();
        idm.kode_barang = txkode_brg.getText();
        idm.nama_barang = txnm_barang.getText();
        idm.kondisi = (String)cbkondisi.getSelectedItem();
        idm.jumlah = txjumlah.getText();
        try{
        idm.simpan();
        JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }ViewData();
    }//GEN-LAST:event_cbsimpanActionPerformed

    private void autonumber(){
        try {
            conn = koneksi.getKoneksi();
            Statement stt = conn.createStatement();
            String sql="select * from inputdata order by kode_barang desc";
            ResultSet rs = stt.executeQuery(sql);
            if (rs.next()){
                String no_brg = rs.getString("kode_barang").substring(3);
                String AN = "" + (Integer.parseInt(no_brg) + 1);
                String Nol = "";
                
                if(AN.length()==1){
                    Nol = "000";
                } else if(AN.length()==2){
                    Nol = "00";
                } else if(AN.length()==3){
                    Nol = "0";
                } else if(AN.length()==4){
                    Nol = "";
                }
                
                txkode_brg.setText("BRG" + Nol + AN);
                  
            } else {
                txkode_brg.setText("BRG0001");
            }
//            rs.close();
//            conn.close();
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
        
    }
    
    private void txkode_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txkode_brgActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txkode_brgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bkembali;
    private javax.swing.JButton cbedit;
    private javax.swing.JButton cbhapus;
    private javax.swing.JComboBox<String> cbkondisi;
    private javax.swing.JButton cbrefresh;
    private javax.swing.JButton cbsimpan;
    private javax.swing.JComboBox<String> cfilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JTextField txcari;
    private java.awt.TextField txjumlah;
    private java.awt.TextField txkode_brg;
    private java.awt.TextField txnm_barang;
    // End of variables declaration//GEN-END:variables
}
